groups:
    - name: EmbeddedExporterV1
      rules:
        - alert: TraefikBackendDown
          expr: count(traefik_backend_server_up) by (backend) == 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Traefik backend down (instance {{ $labels.instance }})
            description: |-
                All Traefik backends are down
                  VALUE = {{ $value }}
                  LABELS = {{ $labels }}
            runbook: https://github.com/srerun/prometheus-alerts/blob/main/content/runbooks/embedded-exporter-v1/TraefikBackendDown.md
        - alert: TraefikHighHttp4xxErrorRateBackend
          expr: sum(rate(traefik_backend_requests_total{code=~"4.*"}[3m])) by (backend) / sum(rate(traefik_backend_requests_total[3m])) by (backend) * 100 > 5
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Traefik high HTTP 4xx error rate backend (instance {{ $labels.instance }})
            description: |-
                Traefik backend 4xx error rate is above 5%
                  VALUE = {{ $value }}
                  LABELS = {{ $labels }}
            runbook: https://github.com/srerun/prometheus-alerts/blob/main/content/runbooks/embedded-exporter-v1/TraefikHighHttp4xxErrorRateBackend.md
        - alert: TraefikHighHttp5xxErrorRateBackend
          expr: sum(rate(traefik_backend_requests_total{code=~"5.*"}[3m])) by (backend) / sum(rate(traefik_backend_requests_total[3m])) by (backend) * 100 > 5
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Traefik high HTTP 5xx error rate backend (instance {{ $labels.instance }})
            description: |-
                Traefik backend 5xx error rate is above 5%
                  VALUE = {{ $value }}
                  LABELS = {{ $labels }}
            runbook: https://github.com/srerun/prometheus-alerts/blob/main/content/runbooks/embedded-exporter-v1/TraefikHighHttp5xxErrorRateBackend.md
